import JSZip from "jszip";
import { saveAs } from "file-saver";
import { StageState, STAGES } from "./types";
import { extractDomainContext } from "./mock-generator";

export async function exportSpecificationZip(
  projectName: string,
  stages: StageState[],
  userPrompt: string,
  techStackSummary?: string
) {
  const zip = new JSZip();
  const domain = extractDomainContext(userPrompt || "Enterprise Cloud Application");
  const sanitizedProjectName = projectName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "") || `${domain.shortName.toLowerCase()}-specs`;

  // 1. Create .specs folder inside zip
  const specsFolder = zip.folder(".specs") || zip;

  // Build master README.md index
  let readmeIndex = `# ${domain.title || projectName || "Project Specifications"}\n\n`;
  readmeIndex += `> Generated with **SpecFlow AI** Spec-Driven Development Suite on ${new Date().toISOString().split("T")[0]}.\n\n`;

  if (userPrompt) {
    readmeIndex += `## 📋 Requirements Prompt\n\n\`\`\`text\n${userPrompt.trim()}\n\`\`\`\n\n`;
  }

  if (techStackSummary) {
    readmeIndex += `## 🛠️ Architecture & Tech Stack\n\n${techStackSummary.trim()}\n\n`;
  }

  readmeIndex += `## 📑 Specification Suite Index\n\n`;
  readmeIndex += `| Stage | Document | Description |\n`;
  readmeIndex += `| :---: | :--- | :--- |\n`;

  // Add each stage file to .specs and the index
  STAGES.forEach((stageDef) => {
    const stageState = stages.find((s) => s.index === stageDef.index);
    const content = stageState?.content || `# ${stageDef.fileName}\n\n*Pending generation.*`;
    
    // Add file to .specs folder
    specsFolder.file(stageDef.fileName, content);

    // Add entry to root README.md index
    readmeIndex += `| **${stageDef.index.toString().padStart(2, "0")}** | [\`${stageDef.fileName}\`](./.specs/${stageDef.fileName}) | ${stageDef.shortDescription} |\n`;
  });

  // Add root README.md
  zip.file("README.md", readmeIndex);

  // 2. Generate Runnable Prisma Schema (prisma/schema.prisma)
  const prismaSchema = `// Prisma Schema generated by SpecFlow AI
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id            String    @id @default(uuid())
  email         String    @unique
  passwordHash  String    @map("password_hash")
  fullName      String?   @map("full_name")
  role          String    @default("operator")
  isActive      Boolean   @default(true) @map("is_active")
  createdAt     DateTime  @default(now()) @map("created_at")
  updatedAt     DateTime  @updatedAt @map("updated_at")

  @@map("users")
}

${domain.primaryEntities.map((ent) => `model ${ent} {
  id          String    @id @default(uuid())
  name        String
  status      String    @default("active")
  metadata    Json?
  createdAt   DateTime  @default(now()) @map("created_at")
  updatedAt   DateTime  @updatedAt @map("updated_at")

  @@map("${ent.toLowerCase()}s")
}`).join("\n\n")}
`;
  zip.file("prisma/schema.prisma", prismaSchema);

  // 3. Generate OpenAPI 3.1 Contract (openapi.json)
  const openApiSpec = {
    openapi: "3.1.0",
    info: {
      title: `${domain.title} REST API`,
      version: "1.0.0",
      description: `Production API contract for ${domain.title} generated by SpecFlow AI.`
    },
    paths: {
      [domain.apiPrefix]: {
        get: {
          summary: `List ${domain.primaryEntities[0]} records`,
          responses: {
            "200": {
              description: "Successful query",
              content: { "application/json": { schema: { type: "object" } } }
            }
          }
        },
        post: {
          summary: `Create a new ${domain.primaryEntities[0]}`,
          requestBody: {
            required: true,
            content: { "application/json": { schema: { type: "object" } } }
          },
          responses: {
            "201": { description: "Resource created successfully" }
          }
        }
      }
    }
  };
  zip.file("openapi.json", JSON.stringify(openApiSpec, null, 2));

  // 4. Generate Production Dockerfile & docker-compose.yml
  const dockerfile = `FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
EXPOSE 3000
CMD ["node", "server.js"]
`;
  zip.file("Dockerfile", dockerfile);

  const dockerCompose = `version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/${domain.shortName.toLowerCase()}_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${domain.shortName.toLowerCase()}_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:
`;
  zip.file("docker-compose.yml", dockerCompose);

  // 5. Generate Playwright E2E Master Test
  const playwrightTest = `import { test, expect } from "@playwright/test";

test.describe("${domain.title} - E2E Master Workflow", () => {
  test("TC-01: End-to-end user journey verification", async ({ page }) => {
    await page.goto("/");
    await expect(page).toHaveTitle(/.*${domain.shortName}.*/i);
  });
});
`;
  zip.file("tests/e2e/workflow.spec.ts", playwrightTest);

  // 6. Generate Quickstart Setup Script
  const quickstartScript = `#!/usr/bin/env bash
# Quickstart script to inspect project specifications
echo "=========================================="
echo " ${domain.title} Specification & Scaffold Suite"
echo "=========================================="
echo "Generated files:"
echo " - .specs/ (All 6 SDLC Specification Markdown files)"
echo " - prisma/schema.prisma (PostgreSQL Database models)"
echo " - openapi.json (OpenAPI 3.1 REST API Specification)"
echo " - Dockerfile & docker-compose.yml"
echo " - tests/e2e/workflow.spec.ts"
`;
  zip.file("quickstart.sh", quickstartScript);

  // Generate zip blob and trigger browser download
  const blob = await zip.generateAsync({ type: "blob" });
  saveAs(blob, `${sanitizedProjectName}.zip`);
}
